### ISSUE TITLE
Many things are broken since commit 2a4d61e

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#476]
- [x]  zoom doesn't work (fixed by #480)
- [x] window.open doesn't work (`mozbrowseropenwindow` event) (see PR #483)
- [x] open in a new tab doesn't work (`mozbrowseropentab` event) (see PR #483)
- [ ] session restore breaks most of the time (see issue #486)
- [ ] windows don't close (if requested from content) (`mozbrowserclosewindow`) (See issue #493)
- [x] stop doesn't work (pressing Escape while page is loading) (See issue #485)

Probably more things…

**Comment by paulrouget** [comment]
For `zoomIn` and `zoomOut`, I think actions from web-shell are not forwarded in `web-view.js:update()`. We get an action that is `instances zoomIn`, but not of `Action`. And I'm not even sure `VisibilityChanged` is ever consumed either. Maybe web-shell should be a service…

Then OpenInBackground is not caught in `web-view.js:update()` either (and there's a `uri -> url` type).

**Comment by gordonbrander** [comment]
Check out `iframe.js`. It looks like `zoom` `VirtualAttribute` is hit when using `accel =` or `accel -`, but the values for `current` and `past` never change from `1`.

**Comment by gordonbrander** [comment]
Also links launched from other apps no longer open in new UI.

**Comment by gordonbrander** [comment]
It looks like actions targeted to a specific ID are "boxed" in an outer `WebView.Action`. Something like `WebView.Action({action: WebView.Open()})`.

`ZoomIn` and `ZoomOut` actions hit the fallback logic at `web-view.js:302`, and you can see that it unboxes these actions before delegating to `updateByID`:

    action instanceof Action ?
          updateByID(state, action.id, action.action) :

**Comment by gordonbrander** [comment]
@Gozala I have a feeling that this is a quick fix... perhaps the message isn't being created the right way? If you have any quick pointers, let us know.

**Comment by gordonbrander** [comment]
@Gozala nvm. Figured out how to fix the page zoom problem https://github.com/mozilla/browser.html/pull/480

**Comment by paulrouget** [comment]
For the session restore issue, I see:

```
Failed to restore a session TypeError: Invalid value for input field: Invalid value for "selection" field:
 Invalid value for "end" field:
 "null" is not a number
```

**Comment by Gozala** [comment]
> 'accel =': _ => WebView.Action({action: Shell.ZoomIn()}),
> But it doesn't change anything.

That should have worked & is a proper way to go about it. I think you may had issue while testing.

**Comment by Gozala** [comment]
>  window.open doesn't work (mozbrowseropenwindow event) (see PR #483)
> open in a new tab doesn't work (mozbrowseropentab event) (see PR #483)

This is fixed by https://github.com/mozilla/browser.html/pull/492

**Comment by gordonbrander** [comment]
Session restore sounds like it might be involved. Let's track the remaining issues using the bugs I filed for them.
