### ISSUE TITLE
Servo + Browser.html: webplatform bugs

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#562]
**P1**

- [ ] can't navigate in iframes: https://github.com/servo/servo/issues/8081 **|** *has patch*
- [ ] style reset doesn't work: https://github.com/servo/servo/issues/9377
- [ ] 1500 RFA per s.: https://github.com/servo/servo/issues/7782
- [ ] shadow blocks clicks: https://github.com/servo/servo/issues/9268
- [ ] scrolling the page scrolls the UI: https://github.com/servo/servo/issues/9306 & https://github.com/servo/servo/issues/9308 & https://github.com/servo/servo/issues/9309

**Webrender P1**
- [ ] favicon not properly rendered: https://github.com/glennw/webrender/issues/143

**P2**

- [ ] loadprogresschange: https://github.com/servo/servo/issues/9382
- [ ] securitychange event: https://github.com/servo/servo/issues/8544
- [ ] iframe.zoom(): https://github.com/servo/servo/issues/8547
- [ ] can't set iframe src after appended to the DOM: https://github.com/servo/servo/issues/7826

**P3**
- [ ] border radius clipping: https://github.com/servo/servo/issues/7575
- [ ] CSS animations/keyframes: https://github.com/servo/servo/issues/8541
- [ ] caret in empty input: https://github.com/servo/servo/issues/8543
- [ ] inline-block issue: https://github.com/servo/servo/issues/8602
- [ ] tiling crash https://github.com/servo/servo/issues/8758
- [ ] update style attribute: https://github.com/servo/servo/issues/9307

Webrender P3:
- [ ] webrender: opacity+transform: https://github.com/glennw/webrender/issues/95
- [ ] opacity transition & pixel ratio: https://github.com/glennw/webrender/issues/103
- [ ] inset shadow: https://github.com/glennw/webrender/issues/105
- [ ] iframe size: https://github.com/glennw/webrender/issues/116

osx titlebar:

- [ ] draggable regions: https://github.com/servo/servo/issues/7408
- [ ] window controls position: https://github.com/servo/servo/issues/7705

We can work around these issues:
- [ ] `vh` not re-computed after resize: https://github.com/servo/servo/issues/8754#issuecomment-160755398
- [ ] window events: https://github.com/servo/servo/issues/6733
- [ ] flex: https://github.com/servo/servo/issues/7304
- [ ] Text selection in `<input>`: https://github.com/servo/servo/issues/8077

Nice to have:
- [ ] overscroll effect: https://github.com/servo/servo/issues/7671

Long run issues:
- [ ] crash: https://github.com/servo/servo/issues/6952
- [ ] 144 navigations limit: https://github.com/servo/servo/issues/7572

Dynamic toolbar support:
- [ ] scroll snapping: https://github.com/servo/servo/issues/7673
- [ ] scrollgrab: https://github.com/servo/servo/issues/7672

____________

**Fixed**

- [x] transformed iframe not properly cropped: https://github.com/glennw/webrender/issues/136
- [x] can't scroll in b.html because of background-size: https://github.com/glennw/webrender/issues/137
- [x] iframe background transparent: https://github.com/glennw/webrender/issues/134
- [x] webrender: can't scroll iframe: https://github.com/glennw/webrender/issues/100
- [x] iframe content not transformed: https://github.com/glennw/webrender/issues/101
- [x] box shadow radius: https://github.com/glennw/webrender/issues/115
- [x] locationchange and redirect: https://github.com/servo/servo/issues/8902
- [x] box-shadow + overflow:hidden: https://github.com/glennw/webrender/issues/124
- [x] border-radius pixelated: https://github.com/glennw/webrender/issues/104
- [x] input event: https://github.com/servo/servo/issues/8613
- [x] iframe.goBack() panics: https://github.com/servo/servo/issues/8674
- [x] iframe.reload(): https://github.com/servo/servo/issues/8575
- [x] previous page not frozen: https://github.com/servo/servo/issues/8673
- [x] iframe and mouse events: https://github.com/glennw/webrender/issues/102
- [x] hit test issue: https://github.com/servo/servo/issues/8759
- [x] hit test issue: https://github.com/servo/servo/issues/8080
- [x] transition initial value is wrong: https://github.com/servo/servo/issues/7816
- [x] 3d transforms cut: https://github.com/servo/servo/issues/8329
- [x] transform + overflow:scroll + iframe: https://github.com/servo/servo/issues/8325
- [x] iconchange event: https://github.com/servo/servo/issues/8347
- [x] inline + transform: https://github.com/servo/servo/issues/7780
- [x] hovering issue: https://github.com/servo/servo/issues/7865
- [x] iframes do not resize: https://github.com/servo/servo/issues/8301
- [x] transform: https://github.com/servo/servo/issues/7779 **|** https://github.com/servo/servo/pull/8266
- [x] overflow: https://github.com/servo/servo/issues/8122 **|** https://github.com/servo/servo/pull/8266
- [x] overflow + iframe: https://github.com/servo/servo/issues/8310
- [x] 3D transform perspective: https://github.com/servo/servo/issues/7797
- [x] subpixel positioning with iframes: https://github.com/servo/servo/issues/8166
- [x] disable default keybings: https://github.com/servo/servo/pull/8121
- [x] support .ico; https://github.com/servo/servo/issues/7666 & https://github.com/servo/servo/issues/3368
- [x] stacking issue with iframes: https://github.com/servo/servo/issues/7796
- [x] scrolling position lost: https://github.com/servo/servo/issues/7864
- [x] flickering: https://github.com/servo/servo/issues/7868
- [x] transform + subpixel: https://github.com/servo/servo/issues/7904
- [x] shadow vs. background: https://github.com/servo/servo/issues/7872
- [x] stacking issue with float: https://github.com/servo/servo/issues/7828
- [x] text color not updated: https://github.com/servo/servo/issues/7814
- [x] slow transitions: https://github.com/servo/servo/issues/7783
- [x] iframe coordinates: https://github.com/servo/servo/issues/7377
- [x] draw in titlebar: https://github.com/servo/servo/issues/7659
- [x] `navigator.platform`: https://github.com/servo/servo/issues/7573
- [x] overflow:hidden: https://github.com/servo/servo/issues/7571
- [x] weakmap crash: https://github.com/servo/servo/issues/7218
- [x] location.reload: https://github.com/servo/servo/pull/7064
- [x] CSS calc: https://github.com/servo/servo/pull/7185
- [x] viewport / devicePixelRatio: https://github.com/servo/servo/pull/6875
- [x] https://github.com/servo/servo/issues/7069
- [x] https://github.com/servo/servo/issues/7067
- [x] #563 
- [x] https://github.com/servo/servo/issues/7071
- [x] https://github.com/servo/servo/issues/7074
- [x] https://github.com/servo/servo/issues/7157
- [x] https://github.com/tomaka/glutin/issues/564
- [x] https://github.com/servo/glutin/pull/44
- [x] https://github.com/servo/servo/pull/7220
- [x] https://github.com/servo/servo/issues/7166
- [x] https://github.com/servo/servo/issues/7282
- [x] https://github.com/servo/servo/issues/7281
- [x] https://github.com/servo/servo/issues/7373
- [x] https://github.com/servo/servo/issues/7372
- [x] 0.5px borders: https://github.com/servo/servo/issues/7665

**Comment by frewsxcv** [comment]
Possibly relevant issue: https://github.com/servo/servo/issues/5394

**Comment by paulrouget** [comment]
I'd like to focus on a minimal servo-based runtime. What we did for Gecko (graphene project).

I see 3 major area of work for now:

* implementing enough of the web standards to be able to render browser.html. For example, `calc()`, `devicePixelRatio`, and fix some layout and painting bugs. I will be filing bugs in servo/servo and reference them here.
* implement enough of the Browser API to support browser.html. There's already an experimental API. Maybe the best way to start is to write tests.
* packaging and OS integration. For example, on osx, we want to create a `.app` package, register the app as a browser at the os level, delegate titlebar drawing to the html app (with the close/minimize/maximize buttons), and so on. I'm thinking of starting with OSX as it's the platform I know best (and already did all of that for gecko). I need to come up with a list of features we need to implement and figure out where they should be implemented (glutin vs. servo's port).

There's a lot more work required. Implementing some missing APIs (indexeddb, settings api, pointer events or gestures...), implement multiprocess, scroll grab, scroll snapping, performance, security model… but I guess we can live without these for now (and some of these tasks are already being worked on).

**Comment by paulrouget** [comment]
I've already started filing bug and I'm working on porting servo to the latest version of glutin (more OS-level features like `with_decoration(false)`).

**Comment by pcwalton** [comment]
Exciting! I'm up for taking down the layout bugs as you come to them (and I've already started on some of the ones you've filed), since they tend to affect Web content too.

**Comment by pcwalton** [comment]
@paulrouget Could you elaborate on why multiprocess is important t

**Comment by paulrouget** [comment]
> @paulrouget Could you elaborate on why multiprocess is important to browser.html?

It is not important. It's not blocking browser.html development. But I assume it will be necessary if we ever ship a product based on servo + browser.html.

**Comment by waddlesplash** [comment]
servo/servo#7067 has been fixed, so that can be checked off.

**Comment by paulrouget** [comment]
@pcwalton, if you have the opportunity to look at some more layout bugs: servo/servo#7166  servo/servo#7281 are the most annoying ones.

**Comment by waddlesplash** [comment]
servo/servo#7571 has been fixed.

**Comment by waddlesplash** [comment]
Oh, also servo/servo#7218 & servo/servo#7064.

**Comment by notriddle** [comment]
servo/servo#7828 is closed.

**Comment by notriddle** [comment]
servo/servo#7780 was fixed by d572f1ca05ca4ae96ca0a7955ab6c05521b5d6d5.

**Comment by notriddle** [comment]
servo/servo#8325 is closed.

**Comment by gordonbrander** [comment]
Draggable regions: servo/servo#7408 ought to be P1, no?

**Comment by paulrouget** [comment]
> Draggable regions: servo/servo#7408 ought to be P1, no?

There's already a draggable zone, it's just not configurable in CSS.

**Comment by gordonbrander** [comment]
> There's already a draggable zone, it's just not configurable in CSS.

NVM :)

**Comment by waddlesplash** [comment]
servo/servo#8329 is fixed.

**Comment by mbrubeck** [comment]
servo/servo#8080 is fixed

**Comment by gordonbrander** [comment]
@paulrouget vh and vw units are not recalculated after window resize https://github.com/servo/servo/issues/8754. P2? We _might_ be able to work around it, but it will be difficult.

**Comment by glennw** [comment]
@paulrouget https://github.com/glennw/webrender/issues/124 is fixed now.

**Comment by glennw** [comment]
@paulrouget https://github.com/glennw/webrender/issues/134 is fixed - however the bug fix was specific to perspective(0) - there is probably still bugs with real (nested) perspective values. I'll be working on those today and tomorrow.

**Comment by glennw** [comment]
@paulrouget https://github.com/glennw/webrender/issues/137 is fixed.

**Comment by glennw** [comment]
@paulrouget https://github.com/glennw/webrender/issues/136 is fixed.

**Comment by paulrouget** [comment]
I'm retiring this meta bug. Maintaining this list is a difficult for many reasons. I will use `A-browserhtml` tags in servo/servo and glennw/webrender for now.

A list summarizing all the browser.html + servo bugs can be found here: http://paulrouget.com/bhtml-servo-issues/
